# Generated by Django 3.0.3 on 2020-04-05 01:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200326_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
