# Generated by Django 3.0.3 on 2020-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200506_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[(' New', 'New'), ('true', 'True'), ('false', 'False ')], max_length=10, null=True),
        ),
    ]
