# Generated by Django 3.0.3 on 2020-05-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200506_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[(' New', 'New'), ('true', 'True'), ('false', 'False ')], default='New', max_length=10),
        ),
    ]
