# Generated by Django 3.0.3 on 2020-06-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
