# Generated by Django 3.0.3 on 2020-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile'),
        ('blog', '0020_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(to='home.userProfile'),
        ),
    ]
