# Generated by Django 3.0.3 on 2020-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200604_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False ')], default='false', max_length=10),
        ),
    ]
